--CREATE PROCEDURE [dbo].[ExerciseProcedure]
--AS
--BEGIN
--SELECT
--	[E_Id], [C_Id], [E_Image], [E_Name], [E_Description], 
--	[E_Pros_1], [E_Pros_2], [E_Pros_3], 
--	[E_Cons_1], [E_Cons_2], [E_Cons_3] 
--FROM Exercises
--END