

CREATE TABLE [dbo].[DietsFoods]
( 
    [D_Id] INT NOT NULL, 
    [F_Id] INT NOT NULL, 
    [Date_Mortified] DATETIME NULL DEFAULT GETUTCDATE() 

    CONSTRAINT FK_DietsFoods_Diets FOREIGN KEY (D_Id) REFERENCES [dbo].Diets(D_Id) ON DELETE CASCADE,
    CONSTRAINT  FK_DietsFoods_Foods FOREIGN KEY (F_ID) REFERENCES [dbo].Foods(F_Id) ON DELETE CASCADE,
    PRIMARY KEY (D_Id, F_Id)
)