// <auto-generated />
using System;
using ExerciseXData_DietLibrary.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExerciseXData_DietLibrary.Migrations
{
    [DbContext(typeof(DietDbContext))]
    [Migration("20241201114613_NewDiet")]
    partial class NewDiet
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ExerciseXData_DietLibrary.Models.DietsFoodsModel", b =>
                {
                    b.Property<int>("DietsD_Id")
                        .HasColumnType("int");

                    b.Property<int?>("FoodsF_Id")
                        .HasColumnType("int");

                    b.Property<string>("DF_Frequency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DF_Modified_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("DF_Recommended_Servings")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DF_Serving_Size")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DF_Total_Calories")
                        .HasColumnType("int");

                    b.HasKey("DietsD_Id", "FoodsF_Id");

                    b.HasIndex("FoodsF_Id");

                    b.ToTable("DietsFoods");

                    b.HasData(
                        new
                        {
                            DietsD_Id = 1,
                            FoodsF_Id = 1,
                            DF_Frequency = "Daily",
                            DF_Modified_Date = new DateTime(2024, 12, 1, 19, 46, 13, 479, DateTimeKind.Local).AddTicks(9711),
                            DF_Recommended_Servings = "2-3 servings/day",
                            DF_Serving_Size = "1 tablespoon",
                            DF_Total_Calories = 119
                        },
                        new
                        {
                            DietsD_Id = 1,
                            FoodsF_Id = 2,
                            DF_Frequency = "Weekly",
                            DF_Modified_Date = new DateTime(2024, 12, 1, 19, 46, 13, 479, DateTimeKind.Local).AddTicks(9713),
                            DF_Recommended_Servings = "2-3 servings/week",
                            DF_Serving_Size = "4 oz",
                            DF_Total_Calories = 232
                        },
                        new
                        {
                            DietsD_Id = 1,
                            FoodsF_Id = 3,
                            DF_Frequency = "Daily",
                            DF_Modified_Date = new DateTime(2024, 12, 1, 19, 46, 13, 479, DateTimeKind.Local).AddTicks(9715),
                            DF_Recommended_Servings = "1-2 servings/day",
                            DF_Serving_Size = "1 cup",
                            DF_Total_Calories = 222
                        },
                        new
                        {
                            DietsD_Id = 1,
                            FoodsF_Id = 4,
                            DF_Frequency = "Daily",
                            DF_Modified_Date = new DateTime(2024, 12, 1, 19, 46, 13, 479, DateTimeKind.Local).AddTicks(9717),
                            DF_Recommended_Servings = "1-2 servings/day",
                            DF_Serving_Size = "1 cup cooked",
                            DF_Total_Calories = 41
                        },
                        new
                        {
                            DietsD_Id = 1,
                            FoodsF_Id = 5,
                            DF_Frequency = "Daily",
                            DF_Modified_Date = new DateTime(2024, 12, 1, 19, 46, 13, 479, DateTimeKind.Local).AddTicks(9719),
                            DF_Recommended_Servings = "1-2 servings/day",
                            DF_Serving_Size = "1 cup",
                            DF_Total_Calories = 60
                        },
                        new
                        {
                            DietsD_Id = 1,
                            FoodsF_Id = 6,
                            DF_Frequency = "Weekly",
                            DF_Modified_Date = new DateTime(2024, 12, 1, 19, 46, 13, 479, DateTimeKind.Local).AddTicks(9721),
                            DF_Recommended_Servings = "3-4 servings/week",
                            DF_Serving_Size = "1/2 cup cooked",
                            DF_Total_Calories = 134
                        },
                        new
                        {
                            DietsD_Id = 1,
                            FoodsF_Id = 7,
                            DF_Frequency = "Daily",
                            DF_Modified_Date = new DateTime(2024, 12, 1, 19, 46, 13, 479, DateTimeKind.Local).AddTicks(9722),
                            DF_Recommended_Servings = "1-2 servings/day",
                            DF_Serving_Size = "1 ounce",
                            DF_Total_Calories = 160
                        },
                        new
                        {
                            DietsD_Id = 1,
                            FoodsF_Id = 8,
                            DF_Frequency = "Daily",
                            DF_Modified_Date = new DateTime(2024, 12, 1, 19, 46, 13, 479, DateTimeKind.Local).AddTicks(9724),
                            DF_Recommended_Servings = "1-2 servings/day",
                            DF_Serving_Size = "1 teaspoon dried",
                            DF_Total_Calories = 3
                        },
                        new
                        {
                            DietsD_Id = 1,
                            FoodsF_Id = 9,
                            DF_Frequency = "Daily",
                            DF_Modified_Date = new DateTime(2024, 12, 1, 19, 46, 13, 479, DateTimeKind.Local).AddTicks(9726),
                            DF_Recommended_Servings = "1-2 servings/day",
                            DF_Serving_Size = "1/2 cup",
                            DF_Total_Calories = 100
                        },
                        new
                        {
                            DietsD_Id = 1,
                            FoodsF_Id = 10,
                            DF_Frequency = "Daily",
                            DF_Modified_Date = new DateTime(2024, 12, 1, 19, 46, 13, 479, DateTimeKind.Local).AddTicks(9728),
                            DF_Recommended_Servings = "1 serving/day",
                            DF_Serving_Size = "5 oz",
                            DF_Total_Calories = 125
                        },
                        new
                        {
                            DietsD_Id = 2,
                            FoodsF_Id = 1,
                            DF_Frequency = "Daily",
                            DF_Modified_Date = new DateTime(2024, 12, 1, 19, 46, 13, 479, DateTimeKind.Local).AddTicks(9730),
                            DF_Recommended_Servings = "1 serving/day",
                            DF_Serving_Size = "1/2 avocado",
                            DF_Total_Calories = 160
                        },
                        new
                        {
                            DietsD_Id = 2,
                            FoodsF_Id = 2,
                            DF_Frequency = "Daily",
                            DF_Modified_Date = new DateTime(2024, 12, 1, 19, 46, 13, 479, DateTimeKind.Local).AddTicks(9732),
                            DF_Recommended_Servings = "3-4 servings/day",
                            DF_Serving_Size = "1 large egg",
                            DF_Total_Calories = 72
                        },
                        new
                        {
                            DietsD_Id = 2,
                            FoodsF_Id = 3,
                            DF_Frequency = "Daily",
                            DF_Modified_Date = new DateTime(2024, 12, 1, 19, 46, 13, 479, DateTimeKind.Local).AddTicks(9733),
                            DF_Recommended_Servings = "1-2 servings/day",
                            DF_Serving_Size = "4 oz",
                            DF_Total_Calories = 187
                        },
                        new
                        {
                            DietsD_Id = 2,
                            FoodsF_Id = 4,
                            DF_Frequency = "Daily",
                            DF_Modified_Date = new DateTime(2024, 12, 1, 19, 46, 13, 479, DateTimeKind.Local).AddTicks(9735),
                            DF_Recommended_Servings = "1-2 servings/day",
                            DF_Serving_Size = "2 slices",
                            DF_Total_Calories = 80
                        },
                        new
                        {
                            DietsD_Id = 2,
                            FoodsF_Id = 5,
                            DF_Frequency = "Daily",
                            DF_Modified_Date = new DateTime(2024, 12, 1, 19, 46, 13, 479, DateTimeKind.Local).AddTicks(9737),
                            DF_Recommended_Servings = "2-3 servings/day",
                            DF_Serving_Size = "1 oz",
                            DF_Total_Calories = 115
                        },
                        new
                        {
                            DietsD_Id = 2,
                            FoodsF_Id = 6,
                            DF_Frequency = "Daily",
                            DF_Modified_Date = new DateTime(2024, 12, 1, 19, 46, 13, 479, DateTimeKind.Local).AddTicks(9739),
                            DF_Recommended_Servings = "2-3 servings/day",
                            DF_Serving_Size = "1 tablespoon",
                            DF_Total_Calories = 119
                        },
                        new
                        {
                            DietsD_Id = 2,
                            FoodsF_Id = 7,
                            DF_Frequency = "Daily",
                            DF_Modified_Date = new DateTime(2024, 12, 1, 19, 46, 13, 479, DateTimeKind.Local).AddTicks(9741),
                            DF_Recommended_Servings = "1 serving/day",
                            DF_Serving_Size = "1 ounce",
                            DF_Total_Calories = 160
                        },
                        new
                        {
                            DietsD_Id = 2,
                            FoodsF_Id = 8,
                            DF_Frequency = "Weekly",
                            DF_Modified_Date = new DateTime(2024, 12, 1, 19, 46, 13, 479, DateTimeKind.Local).AddTicks(9743),
                            DF_Recommended_Servings = "2-3 servings/week",
                            DF_Serving_Size = "4 oz",
                            DF_Total_Calories = 232
                        },
                        new
                        {
                            DietsD_Id = 2,
                            FoodsF_Id = 9,
                            DF_Frequency = "Daily",
                            DF_Modified_Date = new DateTime(2024, 12, 1, 19, 46, 13, 479, DateTimeKind.Local).AddTicks(9744),
                            DF_Recommended_Servings = "2-3 servings/day",
                            DF_Serving_Size = "1 cup",
                            DF_Total_Calories = 25
                        },
                        new
                        {
                            DietsD_Id = 2,
                            FoodsF_Id = 10,
                            DF_Frequency = "Daily",
                            DF_Modified_Date = new DateTime(2024, 12, 1, 19, 46, 13, 479, DateTimeKind.Local).AddTicks(9746),
                            DF_Recommended_Servings = "1-2 servings/day",
                            DF_Serving_Size = "1 medium zucchini",
                            DF_Total_Calories = 33
                        },
                        new
                        {
                            DietsD_Id = 2,
                            FoodsF_Id = 11,
                            DF_Frequency = "Daily",
                            DF_Modified_Date = new DateTime(2024, 12, 1, 19, 46, 13, 479, DateTimeKind.Local).AddTicks(9748),
                            DF_Recommended_Servings = "1-2 servings/day",
                            DF_Serving_Size = "1 cup cooked",
                            DF_Total_Calories = 41
                        },
                        new
                        {
                            DietsD_Id = 2,
                            FoodsF_Id = 12,
                            DF_Frequency = "Daily",
                            DF_Modified_Date = new DateTime(2024, 12, 1, 19, 46, 13, 479, DateTimeKind.Local).AddTicks(9750),
                            DF_Recommended_Servings = "1-2 servings/day",
                            DF_Serving_Size = "1 tablespoon",
                            DF_Total_Calories = 117
                        },
                        new
                        {
                            DietsD_Id = 2,
                            FoodsF_Id = 13,
                            DF_Frequency = "Daily",
                            DF_Modified_Date = new DateTime(2024, 12, 1, 19, 46, 13, 479, DateTimeKind.Local).AddTicks(9752),
                            DF_Recommended_Servings = "1 serving/day",
                            DF_Serving_Size = "1 oz",
                            DF_Total_Calories = 170
                        },
                        new
                        {
                            DietsD_Id = 2,
                            FoodsF_Id = 14,
                            DF_Frequency = "Daily",
                            DF_Modified_Date = new DateTime(2024, 12, 1, 19, 46, 13, 479, DateTimeKind.Local).AddTicks(9753),
                            DF_Recommended_Servings = "1-2 servings/day",
                            DF_Serving_Size = "1 cup cooked",
                            DF_Total_Calories = 35
                        },
                        new
                        {
                            DietsD_Id = 2,
                            FoodsF_Id = 15,
                            DF_Frequency = "Daily",
                            DF_Modified_Date = new DateTime(2024, 12, 1, 19, 46, 13, 479, DateTimeKind.Local).AddTicks(9755),
                            DF_Recommended_Servings = "1-2 servings/day",
                            DF_Serving_Size = "2 tablespoons",
                            DF_Total_Calories = 138
                        },
                        new
                        {
                            DietsD_Id = 3,
                            FoodsF_Id = 1,
                            DF_Frequency = "Daily",
                            DF_Modified_Date = new DateTime(2024, 12, 1, 19, 46, 13, 479, DateTimeKind.Local).AddTicks(9757),
                            DF_Recommended_Servings = "1 serving/day",
                            DF_Serving_Size = "1/2 avocado",
                            DF_Total_Calories = 160
                        },
                        new
                        {
                            DietsD_Id = 3,
                            FoodsF_Id = 2,
                            DF_Frequency = "Daily",
                            DF_Modified_Date = new DateTime(2024, 12, 1, 19, 46, 13, 479, DateTimeKind.Local).AddTicks(9759),
                            DF_Recommended_Servings = "1-2 servings/day",
                            DF_Serving_Size = "4 oz",
                            DF_Total_Calories = 94
                        },
                        new
                        {
                            DietsD_Id = 3,
                            FoodsF_Id = 3,
                            DF_Frequency = "Daily",
                            DF_Modified_Date = new DateTime(2024, 12, 1, 19, 46, 13, 479, DateTimeKind.Local).AddTicks(9761),
                            DF_Recommended_Servings = "2-3 servings/day",
                            DF_Serving_Size = "1/2 cup cooked",
                            DF_Total_Calories = 115
                        },
                        new
                        {
                            DietsD_Id = 3,
                            FoodsF_Id = 4,
                            DF_Frequency = "Daily",
                            DF_Modified_Date = new DateTime(2024, 12, 1, 19, 46, 13, 479, DateTimeKind.Local).AddTicks(9763),
                            DF_Recommended_Servings = "1-2 servings/day",
                            DF_Serving_Size = "1/2 cup cooked",
                            DF_Total_Calories = 135
                        },
                        new
                        {
                            DietsD_Id = 3,
                            FoodsF_Id = 5,
                            DF_Frequency = "Daily",
                            DF_Modified_Date = new DateTime(2024, 12, 1, 19, 46, 13, 479, DateTimeKind.Local).AddTicks(9765),
                            DF_Recommended_Servings = "1-2 servings/day",
                            DF_Serving_Size = "1 cup cooked",
                            DF_Total_Calories = 222
                        },
                        new
                        {
                            DietsD_Id = 3,
                            FoodsF_Id = 6,
                            DF_Frequency = "Daily",
                            DF_Modified_Date = new DateTime(2024, 12, 1, 19, 46, 13, 479, DateTimeKind.Local).AddTicks(9766),
                            DF_Recommended_Servings = "1-2 servings/day",
                            DF_Serving_Size = "1 cup cooked",
                            DF_Total_Calories = 41
                        },
                        new
                        {
                            DietsD_Id = 3,
                            FoodsF_Id = 7,
                            DF_Frequency = "Daily",
                            DF_Modified_Date = new DateTime(2024, 12, 1, 19, 46, 13, 479, DateTimeKind.Local).AddTicks(9768),
                            DF_Recommended_Servings = "1 serving/day",
                            DF_Serving_Size = "1 ounce",
                            DF_Total_Calories = 160
                        },
                        new
                        {
                            DietsD_Id = 3,
                            FoodsF_Id = 8,
                            DF_Frequency = "Daily",
                            DF_Modified_Date = new DateTime(2024, 12, 1, 19, 46, 13, 479, DateTimeKind.Local).AddTicks(9770),
                            DF_Recommended_Servings = "1 serving/day",
                            DF_Serving_Size = "1 medium potato",
                            DF_Total_Calories = 112
                        },
                        new
                        {
                            DietsD_Id = 3,
                            FoodsF_Id = 9,
                            DF_Frequency = "Daily",
                            DF_Modified_Date = new DateTime(2024, 12, 1, 19, 46, 13, 479, DateTimeKind.Local).AddTicks(9772),
                            DF_Recommended_Servings = "1-2 servings/day",
                            DF_Serving_Size = "1 cup cooked",
                            DF_Total_Calories = 55
                        },
                        new
                        {
                            DietsD_Id = 3,
                            FoodsF_Id = 10,
                            DF_Frequency = "Daily",
                            DF_Modified_Date = new DateTime(2024, 12, 1, 19, 46, 13, 479, DateTimeKind.Local).AddTicks(9774),
                            DF_Recommended_Servings = "1-2 servings/day",
                            DF_Serving_Size = "1 medium carrot",
                            DF_Total_Calories = 25
                        },
                        new
                        {
                            DietsD_Id = 3,
                            FoodsF_Id = 11,
                            DF_Frequency = "Daily",
                            DF_Modified_Date = new DateTime(2024, 12, 1, 19, 46, 13, 479, DateTimeKind.Local).AddTicks(9775),
                            DF_Recommended_Servings = "1-2 servings/day",
                            DF_Serving_Size = "1 tablespoon",
                            DF_Total_Calories = 120
                        },
                        new
                        {
                            DietsD_Id = 3,
                            FoodsF_Id = 12,
                            DF_Frequency = "Daily",
                            DF_Modified_Date = new DateTime(2024, 12, 1, 19, 46, 13, 479, DateTimeKind.Local).AddTicks(9810),
                            DF_Recommended_Servings = "1-2 servings/day",
                            DF_Serving_Size = "1/2 cup",
                            DF_Total_Calories = 120
                        },
                        new
                        {
                            DietsD_Id = 3,
                            FoodsF_Id = 13,
                            DF_Frequency = "Daily",
                            DF_Modified_Date = new DateTime(2024, 12, 1, 19, 46, 13, 479, DateTimeKind.Local).AddTicks(9812),
                            DF_Recommended_Servings = "1 serving/day",
                            DF_Serving_Size = "2 tablespoons",
                            DF_Total_Calories = 138
                        },
                        new
                        {
                            DietsD_Id = 3,
                            FoodsF_Id = 14,
                            DF_Frequency = "Daily",
                            DF_Modified_Date = new DateTime(2024, 12, 1, 19, 46, 13, 479, DateTimeKind.Local).AddTicks(9814),
                            DF_Recommended_Servings = "1-2 servings/day",
                            DF_Serving_Size = "1/2 cucumber",
                            DF_Total_Calories = 8
                        },
                        new
                        {
                            DietsD_Id = 3,
                            FoodsF_Id = 15,
                            DF_Frequency = "Daily",
                            DF_Modified_Date = new DateTime(2024, 12, 1, 19, 46, 13, 479, DateTimeKind.Local).AddTicks(9815),
                            DF_Recommended_Servings = "1-2 servings/day",
                            DF_Serving_Size = "1 cup cooked",
                            DF_Total_Calories = 35
                        },
                        new
                        {
                            DietsD_Id = 3,
                            FoodsF_Id = 16,
                            DF_Frequency = "Daily",
                            DF_Modified_Date = new DateTime(2024, 12, 1, 19, 46, 13, 479, DateTimeKind.Local).AddTicks(9817),
                            DF_Recommended_Servings = "1 serving/day",
                            DF_Serving_Size = "1/2 cup",
                            DF_Total_Calories = 100
                        });
                });

            modelBuilder.Entity("ExerciseXData_DietLibrary.Models.DietsModel", b =>
                {
                    b.Property<int>("D_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("D_Id"));

                    b.Property<string>("D_Cons_1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("D_Cons_2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("D_Cons_3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("D_Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("D_Modified_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("D_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("D_Pros_1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("D_Pros_2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("D_Pros_3")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("D_Id");

                    b.ToTable("Diets");

                    b.HasData(
                        new
                        {
                            D_Id = 1,
                            D_Modified_Date = new DateTime(2024, 12, 1, 19, 46, 13, 479, DateTimeKind.Local).AddTicks(9572),
                            D_Name = "Mediterranean Diet"
                        },
                        new
                        {
                            D_Id = 2,
                            D_Modified_Date = new DateTime(2024, 12, 1, 19, 46, 13, 479, DateTimeKind.Local).AddTicks(9579),
                            D_Name = "Keto Diet"
                        },
                        new
                        {
                            D_Id = 3,
                            D_Modified_Date = new DateTime(2024, 12, 1, 19, 46, 13, 479, DateTimeKind.Local).AddTicks(9580),
                            D_Name = "Vegetarian Diet"
                        });
                });

            modelBuilder.Entity("ExerciseXData_DietLibrary.Models.FoodsModel", b =>
                {
                    b.Property<int>("F_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("F_Id"));

                    b.Property<int?>("F_Calories")
                        .HasColumnType("int");

                    b.Property<string>("F_Group")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("F_Image")
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime>("F_Modified_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("F_Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("F_Id");

                    b.ToTable("Foods");

                    b.HasData(
                        new
                        {
                            F_Id = 1,
                            F_Calories = 160,
                            F_Group = "Fruit",
                            F_Modified_Date = new DateTime(2024, 12, 1, 19, 46, 13, 479, DateTimeKind.Local).AddTicks(9664),
                            F_Name = "Avocado"
                        },
                        new
                        {
                            F_Id = 2,
                            F_Calories = 94,
                            F_Group = "Protein",
                            F_Modified_Date = new DateTime(2024, 12, 1, 19, 46, 13, 479, DateTimeKind.Local).AddTicks(9666),
                            F_Name = "Tofu"
                        },
                        new
                        {
                            F_Id = 3,
                            F_Calories = 115,
                            F_Group = "Legume",
                            F_Modified_Date = new DateTime(2024, 12, 1, 19, 46, 13, 479, DateTimeKind.Local).AddTicks(9666),
                            F_Name = "Lentils"
                        },
                        new
                        {
                            F_Id = 4,
                            F_Calories = 135,
                            F_Group = "Legume",
                            F_Modified_Date = new DateTime(2024, 12, 1, 19, 46, 13, 479, DateTimeKind.Local).AddTicks(9668),
                            F_Name = "Chickpeas"
                        },
                        new
                        {
                            F_Id = 5,
                            F_Calories = 222,
                            F_Group = "Grain",
                            F_Modified_Date = new DateTime(2024, 12, 1, 19, 46, 13, 479, DateTimeKind.Local).AddTicks(9669),
                            F_Name = "Quinoa"
                        },
                        new
                        {
                            F_Id = 6,
                            F_Calories = 41,
                            F_Group = "Vegetable",
                            F_Modified_Date = new DateTime(2024, 12, 1, 19, 46, 13, 479, DateTimeKind.Local).AddTicks(9670),
                            F_Name = "Spinach"
                        },
                        new
                        {
                            F_Id = 7,
                            F_Calories = 160,
                            F_Group = "Nut",
                            F_Modified_Date = new DateTime(2024, 12, 1, 19, 46, 13, 479, DateTimeKind.Local).AddTicks(9671),
                            F_Name = "Almonds"
                        },
                        new
                        {
                            F_Id = 8,
                            F_Calories = 112,
                            F_Group = "Vegetable",
                            F_Modified_Date = new DateTime(2024, 12, 1, 19, 46, 13, 479, DateTimeKind.Local).AddTicks(9672),
                            F_Name = "Sweet Potatoes"
                        },
                        new
                        {
                            F_Id = 9,
                            F_Calories = 55,
                            F_Group = "Vegetable",
                            F_Modified_Date = new DateTime(2024, 12, 1, 19, 46, 13, 479, DateTimeKind.Local).AddTicks(9673),
                            F_Name = "Broccoli"
                        },
                        new
                        {
                            F_Id = 10,
                            F_Calories = 25,
                            F_Group = "Vegetable",
                            F_Modified_Date = new DateTime(2024, 12, 1, 19, 46, 13, 479, DateTimeKind.Local).AddTicks(9674),
                            F_Name = "Carrots"
                        },
                        new
                        {
                            F_Id = 11,
                            F_Calories = 120,
                            F_Group = "Oil",
                            F_Modified_Date = new DateTime(2024, 12, 1, 19, 46, 13, 479, DateTimeKind.Local).AddTicks(9675),
                            F_Name = "Avocado Oil"
                        },
                        new
                        {
                            F_Id = 12,
                            F_Calories = 120,
                            F_Group = "Legume",
                            F_Modified_Date = new DateTime(2024, 12, 1, 19, 46, 13, 479, DateTimeKind.Local).AddTicks(9676),
                            F_Name = "Edamame"
                        },
                        new
                        {
                            F_Id = 13,
                            F_Calories = 138,
                            F_Group = "Seed",
                            F_Modified_Date = new DateTime(2024, 12, 1, 19, 46, 13, 479, DateTimeKind.Local).AddTicks(9677),
                            F_Name = "Chia Seeds"
                        },
                        new
                        {
                            F_Id = 14,
                            F_Calories = 8,
                            F_Group = "Vegetable",
                            F_Modified_Date = new DateTime(2024, 12, 1, 19, 46, 13, 479, DateTimeKind.Local).AddTicks(9678),
                            F_Name = "Cucumbers"
                        },
                        new
                        {
                            F_Id = 15,
                            F_Calories = 35,
                            F_Group = "Vegetable",
                            F_Modified_Date = new DateTime(2024, 12, 1, 19, 46, 13, 479, DateTimeKind.Local).AddTicks(9679),
                            F_Name = "Mushrooms"
                        },
                        new
                        {
                            F_Id = 16,
                            F_Calories = 100,
                            F_Group = "Dairy",
                            F_Modified_Date = new DateTime(2024, 12, 1, 19, 46, 13, 479, DateTimeKind.Local).AddTicks(9681),
                            F_Name = "Greek Yogurt"
                        });
                });

            modelBuilder.Entity("ExerciseXData_DietLibrary.Models.DietsFoodsModel", b =>
                {
                    b.HasOne("ExerciseXData_DietLibrary.Models.DietsModel", "Diets")
                        .WithMany("DietsFoods")
                        .HasForeignKey("DietsD_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExerciseXData_DietLibrary.Models.FoodsModel", "Foods")
                        .WithMany("DietsFoods")
                        .HasForeignKey("FoodsF_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Diets");

                    b.Navigation("Foods");
                });

            modelBuilder.Entity("ExerciseXData_DietLibrary.Models.DietsModel", b =>
                {
                    b.Navigation("DietsFoods");
                });

            modelBuilder.Entity("ExerciseXData_DietLibrary.Models.FoodsModel", b =>
                {
                    b.Navigation("DietsFoods");
                });
#pragma warning restore 612, 618
        }
    }
}
