// <auto-generated />
using System;
using ExerciseXData_DietLibrary.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExerciseXData_DietLibrary.Migrations
{
    [DbContext(typeof(DietDbContext))]
    [Migration("20241130235036_NewDiet")]
    partial class NewDiet
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ExerciseXData_DietLibrary.Models.DietsFoodsModel", b =>
                {
                    b.Property<int>("DietsD_Id")
                        .HasColumnType("int");

                    b.Property<int?>("FoodsF_Id")
                        .HasColumnType("int");

                    b.Property<string>("DF_Frequency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DF_Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("DF_Modified_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("DF_Recommended_Servings")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DF_Serving_Size")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DF_Total_Calories")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DietsD_Id", "FoodsF_Id");

                    b.HasIndex("FoodsF_Id");

                    b.ToTable("DietsFoods");
                });

            modelBuilder.Entity("ExerciseXData_DietLibrary.Models.DietsModel", b =>
                {
                    b.Property<int>("D_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("D_Id"));

                    b.Property<string>("D_Cons_1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("D_Cons_2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("D_Cons_3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("D_Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("D_Modified_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("D_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("D_Pros_1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("D_Pros_2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("D_Pros_3")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("D_Id");

                    b.ToTable("Diets");

                    b.HasData(
                        new
                        {
                            D_Id = 1,
                            D_Modified_Date = new DateTime(2024, 12, 1, 7, 50, 36, 638, DateTimeKind.Local).AddTicks(4409),
                            D_Name = "Keto Diet"
                        },
                        new
                        {
                            D_Id = 2,
                            D_Modified_Date = new DateTime(2024, 12, 1, 7, 50, 36, 638, DateTimeKind.Local).AddTicks(4417),
                            D_Name = "Mediterranean Diet"
                        },
                        new
                        {
                            D_Id = 3,
                            D_Modified_Date = new DateTime(2024, 12, 1, 7, 50, 36, 638, DateTimeKind.Local).AddTicks(4418),
                            D_Name = "Vegetarian Diet"
                        });
                });

            modelBuilder.Entity("ExerciseXData_DietLibrary.Models.FoodsModel", b =>
                {
                    b.Property<int>("F_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("F_Id"));

                    b.Property<int?>("F_Calories")
                        .HasColumnType("int");

                    b.Property<string>("F_Group")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("F_Image")
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime>("F_Modified_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("F_Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("F_Id");

                    b.ToTable("Foods");

                    b.HasData(
                        new
                        {
                            F_Id = 1,
                            F_Calories = 160,
                            F_Modified_Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            F_Name = "Avocado"
                        },
                        new
                        {
                            F_Id = 2,
                            F_Calories = 208,
                            F_Modified_Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            F_Name = "Salmon"
                        },
                        new
                        {
                            F_Id = 3,
                            F_Calories = 208,
                            F_Modified_Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            F_Name = "Broccoli "
                        },
                        new
                        {
                            F_Id = 4,
                            F_Calories = 161,
                            F_Modified_Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            F_Name = "Potato "
                        },
                        new
                        {
                            F_Id = 5,
                            F_Calories = 216,
                            F_Modified_Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            F_Name = "Brown rice"
                        },
                        new
                        {
                            F_Id = 6,
                            F_Calories = 205,
                            F_Modified_Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            F_Name = "White rice"
                        },
                        new
                        {
                            F_Id = 7,
                            F_Calories = 76,
                            F_Modified_Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            F_Name = "Tofu "
                        },
                        new
                        {
                            F_Id = 8,
                            F_Calories = 72,
                            F_Modified_Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            F_Name = "Egg"
                        },
                        new
                        {
                            F_Id = 9,
                            F_Calories = 271,
                            F_Modified_Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            F_Name = "Beef steak "
                        },
                        new
                        {
                            F_Id = 10,
                            F_Calories = 165,
                            F_Modified_Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            F_Name = "Chicken breast "
                        },
                        new
                        {
                            F_Id = 11,
                            F_Calories = 271,
                            F_Modified_Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            F_Name = "Beef steak "
                        },
                        new
                        {
                            F_Id = 12,
                            F_Calories = 95,
                            F_Modified_Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            F_Name = "Yogurt  "
                        });
                });

            modelBuilder.Entity("ExerciseXData_DietLibrary.Models.DietsFoodsModel", b =>
                {
                    b.HasOne("ExerciseXData_DietLibrary.Models.DietsModel", "Diets")
                        .WithMany("DietsFoods")
                        .HasForeignKey("DietsD_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExerciseXData_DietLibrary.Models.FoodsModel", "Foods")
                        .WithMany("DietsFoods")
                        .HasForeignKey("FoodsF_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Diets");

                    b.Navigation("Foods");
                });

            modelBuilder.Entity("ExerciseXData_DietLibrary.Models.DietsModel", b =>
                {
                    b.Navigation("DietsFoods");
                });

            modelBuilder.Entity("ExerciseXData_DietLibrary.Models.FoodsModel", b =>
                {
                    b.Navigation("DietsFoods");
                });
#pragma warning restore 612, 618
        }
    }
}
