// <auto-generated />
using System;
using ExerciseXData_DietLibrary.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExerciseXData_DietLibrary.Migrations
{
    [DbContext(typeof(DietDbContext))]
    [Migration("20241201071013_NewDiet")]
    partial class NewDiet
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ExerciseXData_DietLibrary.Models.DietsFoodsModel", b =>
                {
                    b.Property<int>("DietsD_Id")
                        .HasColumnType("int");

                    b.Property<int?>("FoodsF_Id")
                        .HasColumnType("int");

                    b.Property<string>("DF_Frequency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DF_Modified_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("DF_Recommended_Servings")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DF_Serving_Size")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DF_Total_Calories")
                        .HasColumnType("int");

                    b.HasKey("DietsD_Id", "FoodsF_Id");

                    b.HasIndex("FoodsF_Id");

                    b.ToTable("DietsFoods");

                    b.HasData(
                        new
                        {
                            DietsD_Id = 1,
                            FoodsF_Id = 1,
                            DF_Frequency = "Daily",
                            DF_Modified_Date = new DateTime(2024, 12, 1, 15, 10, 13, 443, DateTimeKind.Local).AddTicks(2832),
                            DF_Recommended_Servings = "2-3 servings/day",
                            DF_Serving_Size = "1 tablespoon",
                            DF_Total_Calories = 119
                        },
                        new
                        {
                            DietsD_Id = 1,
                            FoodsF_Id = 2,
                            DF_Frequency = "Weekly",
                            DF_Modified_Date = new DateTime(2024, 12, 1, 15, 10, 13, 443, DateTimeKind.Local).AddTicks(2834),
                            DF_Recommended_Servings = "2-3 servings/week",
                            DF_Serving_Size = "4 oz",
                            DF_Total_Calories = 232
                        },
                        new
                        {
                            DietsD_Id = 1,
                            FoodsF_Id = 3,
                            DF_Frequency = "Daily",
                            DF_Modified_Date = new DateTime(2024, 12, 1, 15, 10, 13, 443, DateTimeKind.Local).AddTicks(2836),
                            DF_Recommended_Servings = "1-2 servings/day",
                            DF_Serving_Size = "1 cup",
                            DF_Total_Calories = 222
                        },
                        new
                        {
                            DietsD_Id = 1,
                            FoodsF_Id = 4,
                            DF_Frequency = "Daily",
                            DF_Modified_Date = new DateTime(2024, 12, 1, 15, 10, 13, 443, DateTimeKind.Local).AddTicks(2838),
                            DF_Recommended_Servings = "1-2 servings/day",
                            DF_Serving_Size = "1 cup cooked",
                            DF_Total_Calories = 41
                        },
                        new
                        {
                            DietsD_Id = 1,
                            FoodsF_Id = 5,
                            DF_Frequency = "Daily",
                            DF_Modified_Date = new DateTime(2024, 12, 1, 15, 10, 13, 443, DateTimeKind.Local).AddTicks(2840),
                            DF_Recommended_Servings = "1-2 servings/day",
                            DF_Serving_Size = "1 cup",
                            DF_Total_Calories = 60
                        },
                        new
                        {
                            DietsD_Id = 1,
                            FoodsF_Id = 6,
                            DF_Frequency = "Weekly",
                            DF_Modified_Date = new DateTime(2024, 12, 1, 15, 10, 13, 443, DateTimeKind.Local).AddTicks(2842),
                            DF_Recommended_Servings = "3-4 servings/week",
                            DF_Serving_Size = "1/2 cup cooked",
                            DF_Total_Calories = 134
                        },
                        new
                        {
                            DietsD_Id = 1,
                            FoodsF_Id = 7,
                            DF_Frequency = "Daily",
                            DF_Modified_Date = new DateTime(2024, 12, 1, 15, 10, 13, 443, DateTimeKind.Local).AddTicks(2843),
                            DF_Recommended_Servings = "1-2 servings/day",
                            DF_Serving_Size = "1 ounce",
                            DF_Total_Calories = 160
                        },
                        new
                        {
                            DietsD_Id = 1,
                            FoodsF_Id = 8,
                            DF_Frequency = "Daily",
                            DF_Modified_Date = new DateTime(2024, 12, 1, 15, 10, 13, 443, DateTimeKind.Local).AddTicks(2845),
                            DF_Recommended_Servings = "1-2 servings/day",
                            DF_Serving_Size = "1 teaspoon dried",
                            DF_Total_Calories = 3
                        },
                        new
                        {
                            DietsD_Id = 1,
                            FoodsF_Id = 9,
                            DF_Frequency = "Daily",
                            DF_Modified_Date = new DateTime(2024, 12, 1, 15, 10, 13, 443, DateTimeKind.Local).AddTicks(2847),
                            DF_Recommended_Servings = "1-2 servings/day",
                            DF_Serving_Size = "1/2 cup",
                            DF_Total_Calories = 100
                        },
                        new
                        {
                            DietsD_Id = 1,
                            FoodsF_Id = 10,
                            DF_Frequency = "Daily",
                            DF_Modified_Date = new DateTime(2024, 12, 1, 15, 10, 13, 443, DateTimeKind.Local).AddTicks(2849),
                            DF_Recommended_Servings = "1 serving/day",
                            DF_Serving_Size = "5 oz",
                            DF_Total_Calories = 125
                        },
                        new
                        {
                            DietsD_Id = 2,
                            FoodsF_Id = 1,
                            DF_Frequency = "Daily",
                            DF_Modified_Date = new DateTime(2024, 12, 1, 15, 10, 13, 443, DateTimeKind.Local).AddTicks(2851),
                            DF_Recommended_Servings = "1 serving/day",
                            DF_Serving_Size = "1/2 avocado",
                            DF_Total_Calories = 160
                        },
                        new
                        {
                            DietsD_Id = 2,
                            FoodsF_Id = 2,
                            DF_Frequency = "Daily",
                            DF_Modified_Date = new DateTime(2024, 12, 1, 15, 10, 13, 443, DateTimeKind.Local).AddTicks(2853),
                            DF_Recommended_Servings = "3-4 servings/day",
                            DF_Serving_Size = "1 large egg",
                            DF_Total_Calories = 72
                        },
                        new
                        {
                            DietsD_Id = 2,
                            FoodsF_Id = 3,
                            DF_Frequency = "Daily",
                            DF_Modified_Date = new DateTime(2024, 12, 1, 15, 10, 13, 443, DateTimeKind.Local).AddTicks(2854),
                            DF_Recommended_Servings = "1-2 servings/day",
                            DF_Serving_Size = "4 oz",
                            DF_Total_Calories = 187
                        },
                        new
                        {
                            DietsD_Id = 2,
                            FoodsF_Id = 4,
                            DF_Frequency = "Daily",
                            DF_Modified_Date = new DateTime(2024, 12, 1, 15, 10, 13, 443, DateTimeKind.Local).AddTicks(2856),
                            DF_Recommended_Servings = "1-2 servings/day",
                            DF_Serving_Size = "2 slices",
                            DF_Total_Calories = 80
                        },
                        new
                        {
                            DietsD_Id = 2,
                            FoodsF_Id = 5,
                            DF_Frequency = "Daily",
                            DF_Modified_Date = new DateTime(2024, 12, 1, 15, 10, 13, 443, DateTimeKind.Local).AddTicks(2858),
                            DF_Recommended_Servings = "2-3 servings/day",
                            DF_Serving_Size = "1 oz",
                            DF_Total_Calories = 115
                        },
                        new
                        {
                            DietsD_Id = 2,
                            FoodsF_Id = 6,
                            DF_Frequency = "Daily",
                            DF_Modified_Date = new DateTime(2024, 12, 1, 15, 10, 13, 443, DateTimeKind.Local).AddTicks(2860),
                            DF_Recommended_Servings = "2-3 servings/day",
                            DF_Serving_Size = "1 tablespoon",
                            DF_Total_Calories = 119
                        },
                        new
                        {
                            DietsD_Id = 2,
                            FoodsF_Id = 7,
                            DF_Frequency = "Daily",
                            DF_Modified_Date = new DateTime(2024, 12, 1, 15, 10, 13, 443, DateTimeKind.Local).AddTicks(2862),
                            DF_Recommended_Servings = "1 serving/day",
                            DF_Serving_Size = "1 ounce",
                            DF_Total_Calories = 160
                        },
                        new
                        {
                            DietsD_Id = 2,
                            FoodsF_Id = 8,
                            DF_Frequency = "Weekly",
                            DF_Modified_Date = new DateTime(2024, 12, 1, 15, 10, 13, 443, DateTimeKind.Local).AddTicks(2863),
                            DF_Recommended_Servings = "2-3 servings/week",
                            DF_Serving_Size = "4 oz",
                            DF_Total_Calories = 232
                        },
                        new
                        {
                            DietsD_Id = 2,
                            FoodsF_Id = 9,
                            DF_Frequency = "Daily",
                            DF_Modified_Date = new DateTime(2024, 12, 1, 15, 10, 13, 443, DateTimeKind.Local).AddTicks(2865),
                            DF_Recommended_Servings = "2-3 servings/day",
                            DF_Serving_Size = "1 cup",
                            DF_Total_Calories = 25
                        },
                        new
                        {
                            DietsD_Id = 2,
                            FoodsF_Id = 10,
                            DF_Frequency = "Daily",
                            DF_Modified_Date = new DateTime(2024, 12, 1, 15, 10, 13, 443, DateTimeKind.Local).AddTicks(2867),
                            DF_Recommended_Servings = "1-2 servings/day",
                            DF_Serving_Size = "1 medium zucchini",
                            DF_Total_Calories = 33
                        },
                        new
                        {
                            DietsD_Id = 2,
                            FoodsF_Id = 11,
                            DF_Frequency = "Daily",
                            DF_Modified_Date = new DateTime(2024, 12, 1, 15, 10, 13, 443, DateTimeKind.Local).AddTicks(2872),
                            DF_Recommended_Servings = "1-2 servings/day",
                            DF_Serving_Size = "1 cup cooked",
                            DF_Total_Calories = 41
                        },
                        new
                        {
                            DietsD_Id = 2,
                            FoodsF_Id = 12,
                            DF_Frequency = "Daily",
                            DF_Modified_Date = new DateTime(2024, 12, 1, 15, 10, 13, 443, DateTimeKind.Local).AddTicks(2874),
                            DF_Recommended_Servings = "1-2 servings/day",
                            DF_Serving_Size = "1 tablespoon",
                            DF_Total_Calories = 117
                        },
                        new
                        {
                            DietsD_Id = 2,
                            FoodsF_Id = 13,
                            DF_Frequency = "Daily",
                            DF_Modified_Date = new DateTime(2024, 12, 1, 15, 10, 13, 443, DateTimeKind.Local).AddTicks(2876),
                            DF_Recommended_Servings = "1 serving/day",
                            DF_Serving_Size = "1 oz",
                            DF_Total_Calories = 170
                        },
                        new
                        {
                            DietsD_Id = 2,
                            FoodsF_Id = 14,
                            DF_Frequency = "Daily",
                            DF_Modified_Date = new DateTime(2024, 12, 1, 15, 10, 13, 443, DateTimeKind.Local).AddTicks(2878),
                            DF_Recommended_Servings = "1-2 servings/day",
                            DF_Serving_Size = "1 cup cooked",
                            DF_Total_Calories = 35
                        },
                        new
                        {
                            DietsD_Id = 2,
                            FoodsF_Id = 15,
                            DF_Frequency = "Daily",
                            DF_Modified_Date = new DateTime(2024, 12, 1, 15, 10, 13, 443, DateTimeKind.Local).AddTicks(2879),
                            DF_Recommended_Servings = "1-2 servings/day",
                            DF_Serving_Size = "2 tablespoons",
                            DF_Total_Calories = 138
                        },
                        new
                        {
                            DietsD_Id = 3,
                            FoodsF_Id = 1,
                            DF_Frequency = "Daily",
                            DF_Modified_Date = new DateTime(2024, 12, 1, 15, 10, 13, 443, DateTimeKind.Local).AddTicks(2881),
                            DF_Recommended_Servings = "1 serving/day",
                            DF_Serving_Size = "1/2 avocado",
                            DF_Total_Calories = 160
                        },
                        new
                        {
                            DietsD_Id = 3,
                            FoodsF_Id = 2,
                            DF_Frequency = "Daily",
                            DF_Modified_Date = new DateTime(2024, 12, 1, 15, 10, 13, 443, DateTimeKind.Local).AddTicks(2883),
                            DF_Recommended_Servings = "1-2 servings/day",
                            DF_Serving_Size = "4 oz",
                            DF_Total_Calories = 94
                        },
                        new
                        {
                            DietsD_Id = 3,
                            FoodsF_Id = 3,
                            DF_Frequency = "Daily",
                            DF_Modified_Date = new DateTime(2024, 12, 1, 15, 10, 13, 443, DateTimeKind.Local).AddTicks(2885),
                            DF_Recommended_Servings = "2-3 servings/day",
                            DF_Serving_Size = "1/2 cup cooked",
                            DF_Total_Calories = 115
                        },
                        new
                        {
                            DietsD_Id = 3,
                            FoodsF_Id = 4,
                            DF_Frequency = "Daily",
                            DF_Modified_Date = new DateTime(2024, 12, 1, 15, 10, 13, 443, DateTimeKind.Local).AddTicks(2887),
                            DF_Recommended_Servings = "1-2 servings/day",
                            DF_Serving_Size = "1/2 cup cooked",
                            DF_Total_Calories = 135
                        },
                        new
                        {
                            DietsD_Id = 3,
                            FoodsF_Id = 5,
                            DF_Frequency = "Daily",
                            DF_Modified_Date = new DateTime(2024, 12, 1, 15, 10, 13, 443, DateTimeKind.Local).AddTicks(2889),
                            DF_Recommended_Servings = "1-2 servings/day",
                            DF_Serving_Size = "1 cup cooked",
                            DF_Total_Calories = 222
                        },
                        new
                        {
                            DietsD_Id = 3,
                            FoodsF_Id = 6,
                            DF_Frequency = "Daily",
                            DF_Modified_Date = new DateTime(2024, 12, 1, 15, 10, 13, 443, DateTimeKind.Local).AddTicks(2890),
                            DF_Recommended_Servings = "1-2 servings/day",
                            DF_Serving_Size = "1 cup cooked",
                            DF_Total_Calories = 41
                        },
                        new
                        {
                            DietsD_Id = 3,
                            FoodsF_Id = 7,
                            DF_Frequency = "Daily",
                            DF_Modified_Date = new DateTime(2024, 12, 1, 15, 10, 13, 443, DateTimeKind.Local).AddTicks(2892),
                            DF_Recommended_Servings = "1 serving/day",
                            DF_Serving_Size = "1 ounce",
                            DF_Total_Calories = 160
                        },
                        new
                        {
                            DietsD_Id = 3,
                            FoodsF_Id = 8,
                            DF_Frequency = "Daily",
                            DF_Modified_Date = new DateTime(2024, 12, 1, 15, 10, 13, 443, DateTimeKind.Local).AddTicks(2894),
                            DF_Recommended_Servings = "1 serving/day",
                            DF_Serving_Size = "1 medium potato",
                            DF_Total_Calories = 112
                        },
                        new
                        {
                            DietsD_Id = 3,
                            FoodsF_Id = 9,
                            DF_Frequency = "Daily",
                            DF_Modified_Date = new DateTime(2024, 12, 1, 15, 10, 13, 443, DateTimeKind.Local).AddTicks(2896),
                            DF_Recommended_Servings = "1-2 servings/day",
                            DF_Serving_Size = "1 cup cooked",
                            DF_Total_Calories = 55
                        },
                        new
                        {
                            DietsD_Id = 3,
                            FoodsF_Id = 10,
                            DF_Frequency = "Daily",
                            DF_Modified_Date = new DateTime(2024, 12, 1, 15, 10, 13, 443, DateTimeKind.Local).AddTicks(2897),
                            DF_Recommended_Servings = "1-2 servings/day",
                            DF_Serving_Size = "1 medium carrot",
                            DF_Total_Calories = 25
                        },
                        new
                        {
                            DietsD_Id = 3,
                            FoodsF_Id = 11,
                            DF_Frequency = "Daily",
                            DF_Modified_Date = new DateTime(2024, 12, 1, 15, 10, 13, 443, DateTimeKind.Local).AddTicks(2899),
                            DF_Recommended_Servings = "1-2 servings/day",
                            DF_Serving_Size = "1 tablespoon",
                            DF_Total_Calories = 120
                        },
                        new
                        {
                            DietsD_Id = 3,
                            FoodsF_Id = 12,
                            DF_Frequency = "Daily",
                            DF_Modified_Date = new DateTime(2024, 12, 1, 15, 10, 13, 443, DateTimeKind.Local).AddTicks(2901),
                            DF_Recommended_Servings = "1-2 servings/day",
                            DF_Serving_Size = "1/2 cup",
                            DF_Total_Calories = 120
                        },
                        new
                        {
                            DietsD_Id = 3,
                            FoodsF_Id = 13,
                            DF_Frequency = "Daily",
                            DF_Modified_Date = new DateTime(2024, 12, 1, 15, 10, 13, 443, DateTimeKind.Local).AddTicks(2903),
                            DF_Recommended_Servings = "1 serving/day",
                            DF_Serving_Size = "2 tablespoons",
                            DF_Total_Calories = 138
                        },
                        new
                        {
                            DietsD_Id = 3,
                            FoodsF_Id = 14,
                            DF_Frequency = "Daily",
                            DF_Modified_Date = new DateTime(2024, 12, 1, 15, 10, 13, 443, DateTimeKind.Local).AddTicks(2905),
                            DF_Recommended_Servings = "1-2 servings/day",
                            DF_Serving_Size = "1/2 cucumber",
                            DF_Total_Calories = 8
                        },
                        new
                        {
                            DietsD_Id = 3,
                            FoodsF_Id = 15,
                            DF_Frequency = "Daily",
                            DF_Modified_Date = new DateTime(2024, 12, 1, 15, 10, 13, 443, DateTimeKind.Local).AddTicks(2907),
                            DF_Recommended_Servings = "1-2 servings/day",
                            DF_Serving_Size = "1 cup cooked",
                            DF_Total_Calories = 35
                        },
                        new
                        {
                            DietsD_Id = 3,
                            FoodsF_Id = 16,
                            DF_Frequency = "Daily",
                            DF_Modified_Date = new DateTime(2024, 12, 1, 15, 10, 13, 443, DateTimeKind.Local).AddTicks(2908),
                            DF_Recommended_Servings = "1 serving/day",
                            DF_Serving_Size = "1/2 cup",
                            DF_Total_Calories = 100
                        });
                });

            modelBuilder.Entity("ExerciseXData_DietLibrary.Models.DietsModel", b =>
                {
                    b.Property<int>("D_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("D_Id"));

                    b.Property<string>("D_Cons_1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("D_Cons_2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("D_Cons_3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("D_Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("D_Modified_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("D_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("D_Pros_1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("D_Pros_2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("D_Pros_3")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("D_Id");

                    b.ToTable("Diets");

                    b.HasData(
                        new
                        {
                            D_Id = 1,
                            D_Modified_Date = new DateTime(2024, 12, 1, 15, 10, 13, 443, DateTimeKind.Local).AddTicks(2692),
                            D_Name = "Mediterranean Diet"
                        },
                        new
                        {
                            D_Id = 2,
                            D_Modified_Date = new DateTime(2024, 12, 1, 15, 10, 13, 443, DateTimeKind.Local).AddTicks(2702),
                            D_Name = "Keto Diet"
                        },
                        new
                        {
                            D_Id = 3,
                            D_Modified_Date = new DateTime(2024, 12, 1, 15, 10, 13, 443, DateTimeKind.Local).AddTicks(2703),
                            D_Name = "Vegetarian Diet"
                        });
                });

            modelBuilder.Entity("ExerciseXData_DietLibrary.Models.FoodsModel", b =>
                {
                    b.Property<int>("F_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("F_Id"));

                    b.Property<int?>("F_Calories")
                        .HasColumnType("int");

                    b.Property<string>("F_Group")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("F_Image")
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime>("F_Modified_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("F_Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("F_Id");

                    b.ToTable("Foods");

                    b.HasData(
                        new
                        {
                            F_Id = 1,
                            F_Calories = 160,
                            F_Group = "Fruit",
                            F_Modified_Date = new DateTime(2024, 12, 1, 15, 10, 13, 443, DateTimeKind.Local).AddTicks(2786),
                            F_Name = "Avocado"
                        },
                        new
                        {
                            F_Id = 2,
                            F_Calories = 94,
                            F_Group = "Protein",
                            F_Modified_Date = new DateTime(2024, 12, 1, 15, 10, 13, 443, DateTimeKind.Local).AddTicks(2787),
                            F_Name = "Tofu"
                        },
                        new
                        {
                            F_Id = 3,
                            F_Calories = 115,
                            F_Group = "Legume",
                            F_Modified_Date = new DateTime(2024, 12, 1, 15, 10, 13, 443, DateTimeKind.Local).AddTicks(2788),
                            F_Name = "Lentils"
                        },
                        new
                        {
                            F_Id = 4,
                            F_Calories = 135,
                            F_Group = "Legume",
                            F_Modified_Date = new DateTime(2024, 12, 1, 15, 10, 13, 443, DateTimeKind.Local).AddTicks(2789),
                            F_Name = "Chickpeas"
                        },
                        new
                        {
                            F_Id = 5,
                            F_Calories = 222,
                            F_Group = "Grain",
                            F_Modified_Date = new DateTime(2024, 12, 1, 15, 10, 13, 443, DateTimeKind.Local).AddTicks(2790),
                            F_Name = "Quinoa"
                        },
                        new
                        {
                            F_Id = 6,
                            F_Calories = 41,
                            F_Group = "Vegetable",
                            F_Modified_Date = new DateTime(2024, 12, 1, 15, 10, 13, 443, DateTimeKind.Local).AddTicks(2792),
                            F_Name = "Spinach"
                        },
                        new
                        {
                            F_Id = 7,
                            F_Calories = 160,
                            F_Group = "Nut",
                            F_Modified_Date = new DateTime(2024, 12, 1, 15, 10, 13, 443, DateTimeKind.Local).AddTicks(2793),
                            F_Name = "Almonds"
                        },
                        new
                        {
                            F_Id = 8,
                            F_Calories = 112,
                            F_Group = "Vegetable",
                            F_Modified_Date = new DateTime(2024, 12, 1, 15, 10, 13, 443, DateTimeKind.Local).AddTicks(2794),
                            F_Name = "Sweet Potatoes"
                        },
                        new
                        {
                            F_Id = 9,
                            F_Calories = 55,
                            F_Group = "Vegetable",
                            F_Modified_Date = new DateTime(2024, 12, 1, 15, 10, 13, 443, DateTimeKind.Local).AddTicks(2795),
                            F_Name = "Broccoli"
                        },
                        new
                        {
                            F_Id = 10,
                            F_Calories = 25,
                            F_Group = "Vegetable",
                            F_Modified_Date = new DateTime(2024, 12, 1, 15, 10, 13, 443, DateTimeKind.Local).AddTicks(2796),
                            F_Name = "Carrots"
                        },
                        new
                        {
                            F_Id = 11,
                            F_Calories = 120,
                            F_Group = "Oil",
                            F_Modified_Date = new DateTime(2024, 12, 1, 15, 10, 13, 443, DateTimeKind.Local).AddTicks(2797),
                            F_Name = "Avocado Oil"
                        },
                        new
                        {
                            F_Id = 12,
                            F_Calories = 120,
                            F_Group = "Legume",
                            F_Modified_Date = new DateTime(2024, 12, 1, 15, 10, 13, 443, DateTimeKind.Local).AddTicks(2798),
                            F_Name = "Edamame"
                        },
                        new
                        {
                            F_Id = 13,
                            F_Calories = 138,
                            F_Group = "Seed",
                            F_Modified_Date = new DateTime(2024, 12, 1, 15, 10, 13, 443, DateTimeKind.Local).AddTicks(2799),
                            F_Name = "Chia Seeds"
                        },
                        new
                        {
                            F_Id = 14,
                            F_Calories = 8,
                            F_Group = "Vegetable",
                            F_Modified_Date = new DateTime(2024, 12, 1, 15, 10, 13, 443, DateTimeKind.Local).AddTicks(2800),
                            F_Name = "Cucumbers"
                        },
                        new
                        {
                            F_Id = 15,
                            F_Calories = 35,
                            F_Group = "Vegetable",
                            F_Modified_Date = new DateTime(2024, 12, 1, 15, 10, 13, 443, DateTimeKind.Local).AddTicks(2801),
                            F_Name = "Mushrooms"
                        },
                        new
                        {
                            F_Id = 16,
                            F_Calories = 100,
                            F_Group = "Dairy",
                            F_Modified_Date = new DateTime(2024, 12, 1, 15, 10, 13, 443, DateTimeKind.Local).AddTicks(2802),
                            F_Name = "Greek Yogurt"
                        });
                });

            modelBuilder.Entity("ExerciseXData_DietLibrary.Models.DietsFoodsModel", b =>
                {
                    b.HasOne("ExerciseXData_DietLibrary.Models.DietsModel", "Diets")
                        .WithMany("DietsFoods")
                        .HasForeignKey("DietsD_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExerciseXData_DietLibrary.Models.FoodsModel", "Foods")
                        .WithMany("DietsFoods")
                        .HasForeignKey("FoodsF_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Diets");

                    b.Navigation("Foods");
                });

            modelBuilder.Entity("ExerciseXData_DietLibrary.Models.DietsModel", b =>
                {
                    b.Navigation("DietsFoods");
                });

            modelBuilder.Entity("ExerciseXData_DietLibrary.Models.FoodsModel", b =>
                {
                    b.Navigation("DietsFoods");
                });
#pragma warning restore 612, 618
        }
    }
}
